name = "Create Academy"
author = "fiztingvillain"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c72c9301eab1ddb70aa8962aabec11f414392ea2bfbe1551b8ab07c6f91beb9e"

[versions]
fabric = "0.14.10"
minecraft = "1.18.2"
