name = "Create Academy"
author = "fiztingvillain"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1fe47b8774c95ad0eca4e60673464d29bf2601bddf5e71cc022bd8c7f298e674"

[versions]
fabric = "0.14.10"
minecraft = "1.18.2"
