name = "Create Academy"
author = "fiztingvillain"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ef135bc460126af7a719ba4cfa101d3345e1ec5e131f0e7fe89489749dfc9543"

[versions]
fabric = "0.14.10"
minecraft = "1.18.2"
