name = "Create Academy"
author = "fiztingvillain"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a671d2aea45fbae2c470c178b5bf8cf4bc2e0c008ce77849b4043b2819b9bd55"

[versions]
fabric = "0.14.10"
minecraft = "1.18.2"
