name = "Create Academy"
author = "fiztingvillain"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "98630a7c3cef80e33bf53de412240c23a0d9857fab86cea4b88b8f25d0f8ee61"

[versions]
fabric = "0.14.10"
minecraft = "1.18.2"
